# Use the official Debian image from the Docker Hub
FROM debian

# Set the maintainer label
LABEL maintainer="mostafa@debian.com"

# Run a command to say "Hello There!..."
CMD ["bash", "-c", "echo 'Hello There!...'"]
